import requests
from html.parser import HTMLParser

response = requests.get('https://pokepast.es/fa5004931ee1830d')
response.raise_for_status()
content = response.text.split('\n')
page = iter((content))
# we want pokemon name and moves for now, the rest can be autogenerated
pokemon_pres = [[""]*8]*6
for i in range(6):
    while line := next(page).strip():
        if line.startswith("<pre>"):  # we're at a pokemon
            # Extract the Pokémon name from the line
             # an `<` is encountered 
                # first span is the type
                # second span is the item
                # third is the ability
                # fourth is the level 
                # discard fifth
                # sixth is the actual pokemon type
                # 7 thru 10 are the moves
            if 'class="type-' in line:
                start = line.find('>') + 1  # Find the first '>' and move one character forward
                end = line.find('<', start)  # Find the next '<' after the start
                pokemon_name = line[start:end]  # Extract the substring
                pokemon_pres[i][0] = pokemon_name  # Store the Pokémon name in the array

            # Continue processing other attributes if needed
            line = next(page)
            break
    print(pokemon_pres[i])
    print()
# print(pokemon_pres)